id: P010710
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:59.410358
source_metadata:
  id: bdr:W3CN7030
  title: དམངས་ཡོངས་ཀྱི་ནུས་ཁུངས་གྲོན་ཆུང་དང་བཙོག་འབུད་ཉུང་དུ་གཏོང་རྒྱུའི་སྐོར་གྱི་ལག་དེབ།
  author: ''
  volumes:
    051be2bc85e140bc9bde482d1b93bacf:
      image_group_id: I3CN7032
      title: ''
      volume_number: 1
      total_pages: 80
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
